### ISSUE TITLE
Map Key Requirement for Serializer (Hocon)

### ISSUE THREAD

**Issue by klaidoshka** [A248/DazzleConf#43]
Hello.

This is similar to an issue discussed some time ago for [YAML](https://github.com/A248/DazzleConf/issues/25#issuecomment-860251078), except now it is for Hocon.

```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
        at libs.space.arim.dazzleconf.ext.hocon.HoconConfigurationFactoryImpl.convertMapToHocon(HoconConfigurationFactoryImpl.java:77) ~[system.jar:?]
        at libs.space.arim.dazzleconf.ext.hocon.HoconConfigurationFactoryImpl.convertValueToHocon(HoconConfigurationFactoryImpl.java:88) ~[system.jar:?]
        at libs.space.arim.dazzleconf.ext.hocon.HoconConfigurationFactoryImpl.convertValueToHocon(HoconConfigurationFactoryImpl.java:92) ~[system.jar:?]
        at libs.space.arim.dazzleconf.ext.hocon.HoconConfigurationFactoryImpl.convertMapToHocon(HoconConfigurationFactoryImpl.java:77) ~[system.jar:?]
        at libs.space.arim.dazzleconf.ext.hocon.HoconConfigurationFactoryImpl.writeMap(HoconConfigurationFactoryImpl.java:65) ~[system.jar:?]
        at libs.space.arim.dazzleconf.factory.HumanReadableConfigurationFactory.bufferedWriteMap(HumanReadableConfigurationFactory.java:125) ~[system.jar:?]
        at libs.space.arim.dazzleconf.factory.HumanReadableConfigurationFactory.writeMap(HumanReadableConfigurationFactory.java:114) ~[system.jar:?]
        at libs.space.arim.dazzleconf.factory.ConfigurationFormatFactory.write(ConfigurationFormatFactory.java:184) ~[system.jar:?]
        at libs.space.arim.dazzleconf.helper.ConfigurationHelper.reloadConfigData(ConfigurationHelper.java:102) ~[system.jar:?]
```

Can this be improved? For better experience. 😊

**Comment by A248** [comment]
Unfortunately, HOCON itself does not allow non-String keys. Their API requires that a `Map<String, Object>` is passed, and their implementation checks every key to ensure it's a String, meaning there are no workarounds with generic erasure hacks.
